name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *" # todo dia meia-noite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate stats
        run: |
          curl -o assets/github-stats.svg "https://github-readme-stats.vercel.app/api?username=L3l4ck561&show_icons=true&theme=tokyonight&hide_border=true&include_all_commits=true&count_private=true"
          
          curl -o assets/top-langs.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=L3l4ck561&layout=compact&theme=tokyonight&hide_border=true"

      - name: Commit files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add assets/*.svg
          git commit -m "update stats" || echo "no changes"
          git push